name: Rebase and Publish

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    rebase_and_publish:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.x

          - name: Install Poetry
            run: |
              pip install poetry

          - name: Configure Poetry
            run: |
              poetry config virtualenvs.create false
              poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

          - name: Check if rebase is needed
            id: check_rebase
            run: |
              git remote add upstream https://github.com/r1chardj0n3s/parse
              git fetch upstream
              if git diff --exit-code main upstream/master; then
                echo "No rebase needed."
                echo "REBASE_NEEDED=false" >> $GITHUB_ENV
              else
                echo "Rebase needed."
                echo "REBASE_NEEDED=true" >> $GITHUB_ENV
              fi

          - name: Rebase to upstream master
            run: |
              git remote add upstream https://github.com/r1chardj0n3s/parse
              git fetch upstream
              git checkout main
              git rebase upstream/master

          - name: Build and Publish
            run: |
              poetry install --no-dev
              poetry build
              poetry publish --no-interaction
